import Provider from '@/components/Provider';
import './globals.css'
import { Open_Sans, Roboto } from 'next/font/google'
import { Roboto_Mono } from 'next/font/google'
import ThemeSwitcher from '@/components/ThemeSwitcher';
 
const open = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-open-sans',
});

const roboto = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});
 
export const metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${open.variable} ${roboto.variable}`}>
      <body className='bg-light dark:bg-dark'>
        <Provider>
          {/* <ThemeSwitcher /> */}
          {children}
        </Provider>
      </body>
    </html>
  )
}
